import { branch } from "@/lib/qualifications/build";
import type { QualificationEntry } from "@/lib/qualifications/types";

const CHECKED = "25 Sep 2026";

/**
 * Branches of the postgraduate and super-speciality degrees with enough
 * holders on this site to be worth a page (the floor was ~25 doctors on
 * 25 Sep 2026). Patterns tolerate the spellings the source data uses:
 * "MD (Medicine)", "MD (General Medicine)", "M.D. Physician", "MS (Ortho)".
 */
export const BRANCHES: QualificationEntry[] = [
  branch({
    slug: "md-general-medicine",
    abbr: "MD (General Medicine)",
    name: "MD in General (Internal) Medicine",
    parent: "md",
    specialty: "internal-medicine",
    pattern: "^MD\\(((GENERAL|INTERNAL)?MEDICINE|GENMEDICINE|GENMED)\\)$",
    about: [
      "The MD in General Medicine — internal medicine, on newer certificates — is the postgraduate degree of the physician: three years after the MBBS training in the diagnosis and medical (non-surgical) treatment of adult illness, from diabetes and hypertension to infections, heart failure and the undiagnosed. Its holder is a consultant physician, the specialist a general practitioner refers an adult to when the problem is not obviously surgical or organ-specific, and the entry point to the medical super-specialities: cardiology, neurology, nephrology and gastroenterology are all DMs taken after this degree.",
      "It is the most common MD branch on this site by a wide margin. Profiles record it as MD (Medicine), MD (General Medicine) or MD (Internal Medicine), and all three are counted here; \"MD Physician\" without brackets is a foreign primary degree and is not.",
    ],
    checkedOn: CHECKED,
    related: ["md", "dm-cardiology", "mrcp"],
  }),
  branch({
    slug: "md-paediatrics",
    abbr: "MD (Paediatrics)",
    name: "MD in Paediatrics",
    parent: "md",
    specialty: "paediatrics",
    pattern: "^MD\\((PAEDIATRICS|PEDIATRICS|PAED|PED|PAEDIATRIC|PEDIATRIC)\\)$",
    about: [
      "The MD in Paediatrics is the three-year postgraduate degree in the medicine of children, from the newborn to adolescence. Its holder is a consultant paediatrician: they see sick children in clinic, admit them to hospital, attend deliveries for the newborn, and run the immunisation and growth checks of well children. Neonatology and the other paediatric super-specialities are DMs taken after this degree. The [DCH](/qualifications/dch) is the two-year diploma in the same branch, and many paediatricians on this site hold both.",
    ],
    checkedOn: CHECKED,
    related: ["md", "dch", "dnb"],
  }),
  branch({
    slug: "md-psychiatry",
    abbr: "MD (Psychiatry)",
    name: "MD in Psychiatry",
    parent: "md",
    specialty: "psychiatry",
    pattern: "^MD\\(PSYCHIATRY\\)$",
    about: [
      "The MD in Psychiatry is the three-year postgraduate degree in the diagnosis and treatment of mental illness. Its holder is a psychiatrist — a medical doctor who can prescribe, admit and, where the law allows, treat without consent under the Mental Healthcare Act — which is what distinguishes a psychiatrist from a clinical psychologist, whose qualification is an MPhil or PsyD and whose register is the [RCI](/registers/rehabilitation-council-of-india). The [DPM](/qualifications/dpm) is the two-year diploma in the same branch.",
      "The MD (Psychiatry) is the second most common MD branch on this site, a consequence of the source data rather than of India's supply of psychiatrists, which is thin.",
    ],
    checkedOn: CHECKED,
    related: ["md", "dpm", "dnb"],
  }),
  branch({
    slug: "md-anaesthesiology",
    abbr: "MD (Anaesthesiology)",
    name: "MD in Anaesthesiology",
    parent: "md",
    specialty: "anaesthesiology",
    pattern: "^MD\\((ANAESTHESIA|ANESTHESIA|ANAESTHESIOLOGY|ANESTHESIOLOGY|ANAESTH|ANAES)\\)$",
    about: [
      "The MD in Anaesthesiology is the three-year postgraduate degree in anaesthesia, intensive care and pain. Its holder is a consultant anaesthetist who gives general and regional anaesthesia, manages the patient through surgery, runs intensive care units and pain clinics, and leads resuscitation. The [DA](/qualifications/da) is the two-year diploma in the same branch. Anaesthetists are hospital doctors with little outpatient practice, so they are under-represented on directories relative to their numbers; the profiles here are mostly hospital-attached.",
    ],
    checkedOn: CHECKED,
    related: ["md", "da", "dnb"],
  }),
  branch({
    slug: "md-pathology",
    abbr: "MD (Pathology)",
    name: "MD in Pathology",
    parent: "md",
    specialty: "pathology",
    pattern: "^MD\\((PATHOLOGY|PATH)\\)$",
    about: [
      "The MD in Pathology is the three-year postgraduate degree in laboratory medicine: the examination of blood, tissue and cells to make diagnoses. Its holder is a pathologist who runs a diagnostic laboratory or a hospital department, reports biopsies and blood counts, and signs the reports every other specialist reads. The [DCP](/qualifications/dcp) is the two-year diploma in the same branch. Pathologists are listed on this site under a laboratory speciality and do not usually see patients.",
    ],
    checkedOn: CHECKED,
    related: ["md", "dcp", "md-radiodiagnosis"],
  }),
  branch({
    slug: "md-radiodiagnosis",
    abbr: "MD (Radiodiagnosis)",
    name: "MD in Radiodiagnosis",
    parent: "md",
    specialty: "radiology",
    pattern: "^MD\\((RADIOLOGY|RADIODIAGNOSIS|RADIODIAGNOSIS|RADIOLOGYDIAGNOSIS|RD)\\)$",
    about: [
      "The MD in Radiodiagnosis — written MD (Radiology) on many certificates — is the three-year postgraduate degree in imaging: X-ray, ultrasound, CT, MRI and the image-guided procedures. Its holder is a radiologist, the specialist who performs and reports scans and is registered under the PC-PNDT Act to operate ultrasound; the [DMRD](/qualifications/dmrd) is the two-year diploma in the same branch. It is distinct from the MD in Radiotherapy, which trains the doctors who treat cancer with radiation.",
    ],
    checkedOn: CHECKED,
    related: ["md", "dmrd", "md-pathology"],
  }),
  branch({
    slug: "md-dermatology",
    abbr: "MD (Dermatology)",
    name: "MD in Dermatology, Venereology and Leprosy",
    parent: "md",
    specialty: "dermatology",
    pattern: "^MD\\((DERMATOLOGY|SKINVD|SKINANDVD|DVL|DERMATOLOGYVENEREOLOGY.*|DERM|SKIN)\\)$",
    about: [
      "The MD in Dermatology, Venereology and Leprosy — MD (Skin & VD) on older certificates — is the three-year postgraduate degree in skin disease, sexually transmitted infections and leprosy. Its holder is a dermatologist, and increasingly a cosmetic practitioner as well; the [DVD](/qualifications/dvd) is the two-year diploma in the same branch. Dermatology is worth checking carefully because the cosmetic market attracts practitioners with no dermatology qualification, and the degree line on the profile is the way to tell them apart.",
    ],
    checkedOn: CHECKED,
    related: ["md", "dvd", "dnb"],
  }),
  branch({
    slug: "md-ms-obstetrics-gynaecology",
    abbr: "MD/MS (Obstetrics & Gynaecology)",
    name: "MD or MS in Obstetrics and Gynaecology",
    parent: "ms",
    specialty: "gynaecology",
    pattern: "^(MD|MS)\\((OBS|OBG|GYN|OBST|OBSTETRICS|GYNAE|GYNAEC|GYNAECOLOGY|GYNECOLOGY|OBSANDGYN|OBSGYN|OBSTETRICSANDGYNAECOLOGY|OBSTETRICSGYNAECOLOGY|OBGY|OBGYN).*\\)$",
    about: [
      "The postgraduate degree in obstetrics and gynaecology is awarded as an MS by some universities and an MD by others, for the same three years of training — which is why this page counts both. Its holder is an obstetrician and gynaecologist: they manage pregnancy and delivery, perform caesarean sections and gynaecological surgery, and treat the disorders of the female reproductive system. The [DGO](/qualifications/dgo) is the two-year diploma in the same branch, and many gynaecologists on this site record both. The [MRCOG](/qualifications/mrcog) is the London college's equivalent.",
    ],
    checkedOn: CHECKED,
    related: ["dgo", "ms", "mrcog"],
  }),
  branch({
    slug: "ms-general-surgery",
    abbr: "MS (General Surgery)",
    name: "MS in General Surgery",
    parent: "ms",
    specialty: "general-surgery",
    pattern: "^MS\\((GENERALSURGERY|GENSURG|GENSURGERY|SURGERY|GENERALSURG|SURG)\\)$",
    about: [
      "The MS in General Surgery is the three-year postgraduate degree of the surgeon: training in the operations of the abdomen, the breast, the thyroid, hernias, trauma and the common emergencies, and the base from which the surgical super-specialities — urology, neurosurgery, plastic surgery, surgical gastroenterology and oncology — are entered through the [MCh](/qualifications/mch). Its holder is a general surgeon. It is the most common MS branch on this site, and the surgeons who record it also record laparoscopic fellowships such as the [FMAS](/qualifications/fmas) and [FIAGES](/qualifications/fiages) more than any other group.",
    ],
    checkedOn: CHECKED,
    related: ["ms", "mch", "dnb"],
  }),
  branch({
    slug: "ms-orthopaedics",
    abbr: "MS (Orthopaedics)",
    name: "MS in Orthopaedics",
    parent: "ms",
    specialty: "orthopaedics",
    pattern: "^MS\\((ORTHO|ORTHOPAEDICS|ORTHOPEDICS|ORTHOPAEDIC|ORTHOPEDIC|ORTH)\\)$",
    about: [
      "The MS in Orthopaedics is the three-year postgraduate degree in the surgery of bones, joints and the spine: fractures, joint replacement, arthroscopy, deformity and spinal surgery. Its holder is an orthopaedic surgeon; the [D.Ortho](/qualifications/d-ortho) is the two-year diploma in the same branch, and joint-replacement and spine fellowships are taken after the MS. On this site orthopaedic surgeons record the MS under several spellings — Ortho, Orthopaedics, Orthopedics — and all are counted here.",
    ],
    checkedOn: CHECKED,
    related: ["ms", "d-ortho", "dnb"],
  }),
  branch({
    slug: "ms-ent",
    abbr: "MS (ENT)",
    name: "MS in Otorhinolaryngology (ENT)",
    parent: "ms",
    specialty: "ent",
    pattern: "^MS\\((ENT|OTORHINOLARYNGOLOGY|ORL|OTOLARYNGOLOGY)\\)$",
    about: [
      "The MS in Otorhinolaryngology — ENT — is the three-year postgraduate degree in the surgery and medicine of the ear, nose, throat, head and neck: hearing loss and cochlear implants, sinus and nasal surgery, tonsils and adenoids, voice and swallowing, and the tumours of the head and neck. Its holder is an ENT surgeon; the [DLO](/qualifications/dlo) is the two-year diploma in the same branch. Audiologists, who test hearing and fit hearing aids, are a separate allied profession registered with the [RCI](/registers/rehabilitation-council-of-india).",
    ],
    checkedOn: CHECKED,
    related: ["ms", "dlo", "dnb"],
  }),
  branch({
    slug: "ms-ophthalmology",
    abbr: "MS (Ophthalmology)",
    name: "MS in Ophthalmology",
    parent: "ms",
    specialty: "ophthalmology",
    pattern: "^MS\\((OPHTHALMOLOGY|OPHTHAL|OPTHALMOLOGY|OPHTH|OPTHAL|OPHTHALMOLOGYSURGERY)\\)$",
    about: [
      "The MS in Ophthalmology is the three-year postgraduate degree in the medicine and surgery of the eye: cataract, glaucoma, retina, cornea, squint and the eye in diabetes. Its holder is an ophthalmologist — an eye surgeon — which distinguishes them from an optometrist, who tests sight and prescribes spectacles and is not a medical doctor. The [DOMS](/qualifications/doms) is the two-year diploma in the same branch. Retina, cornea and paediatric ophthalmology are fellowships taken after the MS.",
    ],
    checkedOn: CHECKED,
    related: ["ms", "doms", "dnb"],
  }),
  branch({
    slug: "dm-cardiology",
    abbr: "DM (Cardiology)",
    name: "DM in Cardiology",
    parent: "dm",
    specialty: "cardiology",
    pattern: "^DM\\((CARDIOLOGY|CARDIO|CARD)\\)$",
    about: [
      "The DM in Cardiology is the super-speciality degree of the heart physician: three years after an MD or DNB in medicine, training in the diagnosis and treatment of heart disease, angiography and angioplasty, pacemakers and heart failure. Its holder is a cardiologist in the sense the register uses. A cardiothoracic surgeon — the doctor who performs bypass and valve surgery — holds the [MCh in CVTS](/qualifications/mch-cvts) instead, and a physician with a heart interest holds neither. The DrNB (Cardiology) is the National Board's equivalent and is counted on the [DrNB](/qualifications/drnb) page.",
      "The DM (Cardiology) is the most common DM branch on this site, and Bengaluru's corporate hospitals account for much of it.",
    ],
    checkedOn: CHECKED,
    related: ["dm", "mch-cvts", "md-general-medicine"],
  }),
  branch({
    slug: "dm-neurology",
    abbr: "DM (Neurology)",
    name: "DM in Neurology",
    parent: "dm",
    specialty: "neurology",
    pattern: "^DM\\((NEUROLOGY|NEURO)\\)$",
    about: [
      "The DM in Neurology is the super-speciality degree of the brain-and-nerve physician: three years after an MD or DNB in medicine, training in stroke, epilepsy, headache, Parkinson's disease, dementia, neuropathies and the rest of neurological medicine. Its holder is a neurologist, who diagnoses and treats but does not operate; the surgeon of the brain and spine is the neurosurgeon, who holds the [MCh in Neurosurgery](/qualifications/mch-neurosurgery). Patients confuse the two constantly, and the degree on the profile is the way to tell them apart.",
    ],
    checkedOn: CHECKED,
    related: ["dm", "mch-neurosurgery", "md-general-medicine"],
  }),
  branch({
    slug: "dm-nephrology",
    abbr: "DM (Nephrology)",
    name: "DM in Nephrology",
    parent: "dm",
    specialty: "nephrology",
    pattern: "^DM\\((NEPHROLOGY|NEPHRO)\\)$",
    about: [
      "The DM in Nephrology is the super-speciality degree of the kidney physician: three years after an MD or DNB in medicine, training in kidney disease, dialysis and the medical care of transplant patients. Its holder is a nephrologist. The surgeon who operates on the kidney and urinary tract is the urologist, who holds the [MCh in Urology](/qualifications/mch-urology); a transplant involves both. Nephrologists on this site are few and concentrated in the big hospitals.",
    ],
    checkedOn: CHECKED,
    related: ["dm", "mch-urology", "md-general-medicine"],
  }),
  branch({
    slug: "dm-gastroenterology",
    abbr: "DM (Gastroenterology)",
    name: "DM in Gastroenterology",
    parent: "dm",
    specialty: "gastroenterology",
    pattern: "^DM\\((GASTROENTEROLOGY|GASTRO|MEDICALGASTROENTEROLOGY|GASTROENTROLOGY)\\)$",
    about: [
      "The DM in Gastroenterology is the super-speciality degree of the digestive-system physician: three years after an MD or DNB in medicine, training in the diseases of the stomach, intestines, liver and pancreas, and in endoscopy. Its holder is a gastroenterologist, who scopes and treats but does not operate; the surgeon of the same organs is the surgical gastroenterologist, an MCh holder. Hepatology, the medicine of the liver, is a further DM in some centres.",
    ],
    checkedOn: CHECKED,
    related: ["dm", "md-general-medicine", "mch"],
  }),
  branch({
    slug: "mch-neurosurgery",
    abbr: "MCh (Neurosurgery)",
    name: "MCh in Neurosurgery",
    parent: "mch",
    specialty: "neurosurgery",
    pattern: "^MCH\\((NEUROSURGERY|NEURO|NEUROSURG)\\)$",
    about: [
      "The MCh in Neurosurgery is the super-speciality degree of the brain and spine surgeon: three years after an MS or DNB in general surgery (six in the direct courses), training in the surgery of brain tumours, head injury, aneurysms, the spine and the peripheral nerves. Its holder is a neurosurgeon. The physician of the same organs is the neurologist, who holds the [DM in Neurology](/qualifications/dm-neurology) and does not operate. It is the most common MCh branch on this site.",
    ],
    checkedOn: CHECKED,
    related: ["mch", "dm-neurology", "ms-general-surgery"],
  }),
  branch({
    slug: "mch-urology",
    abbr: "MCh (Urology)",
    name: "MCh in Urology",
    parent: "mch",
    specialty: "urology",
    pattern: "^MCH\\((UROLOGY|URO|GENITOURINARYSURGERY|UROLOGYGENITOURINARYSURGERY)\\)$",
    about: [
      "The MCh in Urology is the super-speciality degree of the surgeon of the kidney, bladder, prostate and male reproductive organs: three years after an MS or DNB in general surgery, training in stone surgery, prostate surgery, urological cancer and kidney transplantation. Its holder is a urologist. The physician of the kidney is the nephrologist, who holds the [DM in Nephrology](/qualifications/dm-nephrology); they work together on transplant and dialysis patients.",
    ],
    checkedOn: CHECKED,
    related: ["mch", "dm-nephrology", "ms-general-surgery"],
  }),
  branch({
    slug: "mch-plastic-surgery",
    abbr: "MCh (Plastic Surgery)",
    name: "MCh in Plastic and Reconstructive Surgery",
    parent: "mch",
    specialty: "plastic-surgery",
    pattern: "^MCH\\((PLASTICSURGERY|PLASTIC|PLASTICANDRECONSTRUCTIVESURGERY|PLASTICRECONSTRUCTIVESURGERY|BURNSANDPLASTICSURGERY)\\)$",
    about: [
      "The MCh in Plastic Surgery is the super-speciality degree of the reconstructive and cosmetic surgeon: three years after an MS or DNB in general surgery, training in burns, hand surgery, microsurgery, cleft and craniofacial repair, and the aesthetic procedures. Its holder is a plastic surgeon. The cosmetic market is crowded with practitioners who are not — dermatologists doing procedures within their field, and others with no surgical qualification at all — and the MCh on the profile is what distinguishes a plastic surgeon from a \"cosmetic surgeon\" who may hold nothing of the kind.",
    ],
    checkedOn: CHECKED,
    related: ["mch", "md-dermatology", "ms-general-surgery"],
  }),
  branch({
    slug: "mch-cvts",
    abbr: "MCh (CVTS)",
    name: "MCh in Cardiovascular and Thoracic Surgery",
    parent: "mch",
    specialty: "cardiothoracic-surgery",
    pattern: "^MCH\\((CVTS|CTVS|CARDIOTHORACICSURGERY|CARDIOTHORACICANDVASCULARSURGERY|CARDIOVASCULARANDTHORACICSURGERY|CARDIOTHORACICVASCULARSURGERY|CTS)\\)$",
    about: [
      "The MCh in Cardiovascular and Thoracic Surgery — CVTS, or CTVS on some certificates — is the super-speciality degree of the heart and chest surgeon: three years after an MS or DNB in general surgery, training in coronary bypass, valve surgery, congenital heart surgery, lung surgery and the surgery of the great vessels. Its holder is a cardiothoracic surgeon. The physician of the heart is the cardiologist, who holds the [DM in Cardiology](/qualifications/dm-cardiology) and does angioplasty but not open surgery; a heart patient is usually under both.",
    ],
    checkedOn: CHECKED,
    related: ["mch", "dm-cardiology", "ms-general-surgery"],
  }),
  branch({
    slug: "mds-orthodontics",
    abbr: "MDS (Orthodontics)",
    name: "MDS in Orthodontics and Dentofacial Orthopaedics",
    parent: "mds",
    specialty: "dentistry",
    pattern: "^MDS\\((ORTHODONTICS|ORTHO|ORTHODONTIA|ORTHODONTICSANDDENTOFACIALORTHOPAEDICS|ORTHODONTICSDENTOFACIALORTHOPEDICS)\\)$",
    about: [
      "The MDS in Orthodontics and Dentofacial Orthopaedics is the three-year postgraduate dental degree in the alignment of teeth and jaws: braces, aligners and the correction of bite. Its holder is an orthodontist. Any dentist may fit braces; an orthodontist has trained for three further years in nothing else, and the MDS on the profile is what tells you which you are seeing. It is the most common MDS branch on this site.",
    ],
    checkedOn: CHECKED,
    related: ["mds", "bds", "mds-oral-maxillofacial-surgery"],
  }),
  branch({
    slug: "mds-oral-maxillofacial-surgery",
    abbr: "MDS (Oral & Maxillofacial Surgery)",
    name: "MDS in Oral and Maxillofacial Surgery",
    parent: "mds",
    specialty: "dentistry",
    pattern: "^MDS\\((ORALMAXILLOFACIALSURGERY|MAXILLOFACIALSURGERY|ORALANDMAXILLOFACIALSURGERY|OMFS|ORALSURGERY|OMS)\\)$",
    about: [
      "The MDS in Oral and Maxillofacial Surgery is the three-year postgraduate dental degree in the surgery of the mouth, jaws and face: impacted wisdom teeth, jaw fractures, cysts and tumours of the jaw, dental implants and corrective jaw surgery. Its holder is an oral and maxillofacial surgeon, a dental specialist who operates, often in a hospital and often alongside plastic and ENT surgeons on facial injuries. The [MDS](/qualifications/mds) page covers the degree; this page counts the surgeons.",
    ],
    checkedOn: CHECKED,
    related: ["mds", "mds-orthodontics", "bds"],
  }),
];
