import { SOURCE_NMC_COURSES, SOURCE_NMC_IMR, SOURCE_NMC_PGMER, qualification } from "@/lib/qualifications/build";
import type { QualificationEntry } from "@/lib/qualifications/types";

const CHECKED = "25 Sep 2026";
const NMC = "national-medical-commission";

/** Degrees of modern medicine: the primary degree, the postgraduate degrees, the super-specialities. */
export const MODERN_DEGREES: QualificationEntry[] = [
  qualification({
    slug: "mbbs",
    abbr: "MBBS",
    name: "Bachelor of Medicine, Bachelor of Surgery",
    kind: "primary",
    system: "modern",
    awardedBy: "Universities, under the NMC's Graduate Medical Education Regulations",
    duration: "4½ years plus a one-year compulsory rotating internship",
    entry: "NEET-UG",
    registerSlug: NMC,
    pattern: "^MBBS$",
    standfirst: "The MBBS is the primary medical degree in India — the one that puts a doctor on the medical register. What it is, what it is not, and who here holds it.",
    about: [
      "The MBBS is the qualification that makes someone a doctor of modern medicine in India. It is a university degree of four and a half years of study followed by a compulsory rotating internship of one year, taught under the National Medical Commission's Graduate Medical Education Regulations (the current set is dated 2023) and entered through NEET-UG. A graduate registers provisionally with a state medical council for the internship and permanently after it; that permanent registration is what the [Indian Medical Register](/registers/national-medical-commission) records, and the MBBS is the qualification recorded against it.",
      "Two things the MBBS is not. It is not a specialist qualification: an MBBS holder is a general physician, and the postgraduate degrees — [MD](/qualifications/md), [MS](/qualifications/ms), [DNB](/qualifications/dnb) — are what make a specialist. And it is not the only route onto the register: a doctor who qualified abroad sits the screening test and registers on that basis, and the register may then show a foreign primary degree (an MD from a Russian or Chinese university, say) that is equivalent to the MBBS rather than to the Indian postgraduate MD of the same name.",
      "On this site the MBBS is recorded on the great majority of modern-medicine profiles, usually as the first qualification in the list. Where a profile records no primary degree at all, the page says so rather than assuming one.",
    ],
    extraFaqs: [
      {
        q: "Is a foreign MD the same as an Indian MD?",
        a: "Usually not. Many countries award an \"MD\" as the primary medical degree, equivalent to the Indian MBBS; the Indian MD is a postgraduate specialist degree taken after the MBBS. A doctor who trained abroad and holds a foreign MD as their only degree is a general physician, not a specialist, and the register entry will show the degree as the primary qualification.",
      },
      {
        q: "Can someone practise medicine in India with a degree other than the MBBS?",
        a: "Modern medicine, no: registration with a state medical council requires the MBBS or a recognised equivalent primary degree. Other systems have their own primary degrees — the BDS for dentistry, the BAMS, BUMS and BHMS for Ayurveda, Unani and Homoeopathy — and their own registers, and each licenses practice of that system only.",
      },
    ],
    checkedOn: CHECKED,
    sources: [SOURCE_NMC_IMR, SOURCE_NMC_COURSES, SOURCE_NMC_PGMER],
    related: ["md", "ms", "dnb"],
  }),
  qualification({
    slug: "md",
    abbr: "MD",
    name: "Doctor of Medicine",
    kind: "postgraduate",
    system: "modern",
    awardedBy: "Universities, under the NMC's Post-Graduate Medical Education Regulations",
    duration: "3 years after MBBS",
    entry: "NEET-PG",
    registerSlug: NMC,
    pattern: "^MD(\\((?!AYU|HOM|ALTERNATIVE|AM\\)|UNANI|SIDDHA|PHYSICIAN)|$)",
    standfirst: "The MD is the three-year postgraduate degree of the medical specialities — general medicine, paediatrics, psychiatry, anaesthesia and the rest.",
    about: [
      "In India the MD is a postgraduate degree, not a primary one. It is taken after the MBBS, entered through NEET-PG, and lasts three years — the minimum the National Medical Commission's Post-Graduate Medical Education Regulations, 2023 set for a broad-speciality degree. It is awarded in the medical rather than the surgical specialities: general medicine, paediatrics, psychiatry, anaesthesiology, pathology, radiodiagnosis, dermatology, community medicine, pharmacology and others. The surgical counterpart is the [MS](/qualifications/ms), and the [DNB](/qualifications/dnb) is the same level of training examined by the National Board rather than a university.",
      "The branch is the important part. \"MD\" alone tells you the doctor is a specialist; \"MD (Psychiatry)\" tells you in what. Profiles on this site record the branch where the source data carried it, and the measured block below shows which branches the MDs here are in. A doctor whose MD is in a non-clinical branch — pathology, microbiology, pharmacology — is a specialist in that branch, and will usually be listed under a laboratory or non-clinical speciality rather than as a treating physician.",
      "Two names to keep apart. An MD from a university abroad is very often the primary medical degree, equivalent to the MBBS; and the MD in Ayurveda or Homoeopathy is a postgraduate degree in that system, registrable with an AYUSH board rather than a medical council. Neither is counted on this page.",
    ],
    extraFaqs: [
      {
        q: "Is an MD better than a DNB?",
        a: "They are the same level. The DNB is awarded by the National Board of Examinations in Medical Sciences after the same three years of training, and the NMC recognises it as equivalent to the MD and MS. The conditions attached to teaching appointments have shifted over the years and are set by the NMC's teacher-eligibility regulations; for a patient, the two are interchangeable.",
      },
    ],
    checkedOn: CHECKED,
    sources: [SOURCE_NMC_PGMER, SOURCE_NMC_IMR, SOURCE_NMC_COURSES],
    related: ["ms", "dnb", "dm"],
  }),
  qualification({
    slug: "ms",
    abbr: "MS",
    name: "Master of Surgery",
    kind: "postgraduate",
    system: "modern",
    awardedBy: "Universities, under the NMC's Post-Graduate Medical Education Regulations",
    duration: "3 years after MBBS",
    entry: "NEET-PG",
    registerSlug: NMC,
    pattern: "^MS(\\(|$)",
    standfirst: "The MS is the three-year postgraduate degree of the surgical specialities — general surgery, orthopaedics, ENT, ophthalmology and gynaecology.",
    about: [
      "The MS is the surgical counterpart of the [MD](/qualifications/md): a three-year postgraduate degree after the MBBS, entered through NEET-PG, awarded by universities under the National Medical Commission's Post-Graduate Medical Education Regulations, 2023. Its branches are the broad surgical specialities — general surgery, orthopaedics, otorhinolaryngology (ENT), ophthalmology, and obstetrics and gynaecology, which is awarded as either MS or MD depending on the university — plus anatomy, which is a non-clinical MS.",
      "As with the MD, the branch is what matters and it is usually written in brackets after the degree. An MS (General Surgery) holder is a general surgeon; the [MCh](/qualifications/mch) is the further three years that make a super-specialist — a urologist, a neurosurgeon, a plastic surgeon. The measured block below shows which branches the MS holders on this site record and where they practise.",
    ],
    extraFaqs: [
      {
        q: "Is an MS the same as an MS in engineering or science?",
        a: "No. The medical MS is a postgraduate surgical degree that requires an MBBS to enter and three years of clinical training to complete. It shares only its initials with the Master of Science.",
      },
    ],
    checkedOn: CHECKED,
    sources: [SOURCE_NMC_PGMER, SOURCE_NMC_IMR, SOURCE_NMC_COURSES],
    related: ["md", "mch", "dnb"],
  }),
  qualification({
    slug: "dnb",
    abbr: "DNB",
    name: "Diplomate of National Board",
    kind: "postgraduate",
    system: "modern",
    awardedBy: "National Board of Examinations in Medical Sciences",
    duration: "3 years after MBBS (2 years after a recognised PG diploma)",
    entry: "NEET-PG",
    registerSlug: NMC,
    pattern: "^DNB(\\(|$)",
    standfirst: "The DNB is a postgraduate qualification examined by the National Board rather than a university, and recognised as equivalent to the MD and MS.",
    about: [
      "The Diplomate of National Board is a postgraduate qualification awarded by the National Board of Examinations in Medical Sciences (NBEMS), a body under the health ministry, rather than by a university. Training runs in accredited hospitals — many of them private and corporate hospitals with no medical college attached — for three years after the MBBS, or two after a recognised postgraduate diploma, and entry is through NEET-PG, the same examination as for the MD and MS. The examination at the end is the National Board's own.",
      "The National Medical Commission recognises the DNB as a postgraduate qualification equivalent to the MD and MS in the same branch; the conditions attached to teaching appointments have moved over the years and are set by the NMC's teacher-eligibility regulations, not by the degree itself. For a patient, a DNB (Paediatrics) and an MD (Paediatrics) mean the same thing: a specialist trained for three years and examined nationally.",
      "The Board also awards the [DrNB](/qualifications/drnb) for super-specialities, equivalent to the DM and MCh, and the [FNB](/qualifications/fnb), a fellowship in a narrower field. Because DNB training is hospital-based, DNB holders are common in the big corporate hospitals on this site, and the measured block below shows the branches and cities.",
    ],
    extraFaqs: [
      {
        q: "Is a DNB a diploma?",
        a: "Despite the word \"Diplomate\", no. It is a three-year postgraduate qualification at the same level as the MD and MS. The two-year postgraduate diplomas — DGO, DCH, DA and the rest — are a different thing.",
      },
    ],
    checkedOn: CHECKED,
    sources: [SOURCE_NMC_PGMER, SOURCE_NMC_IMR],
    related: ["md", "ms", "drnb", "fnb"],
  }),
  qualification({
    slug: "dm",
    abbr: "DM",
    name: "Doctorate of Medicine",
    kind: "superspecialty",
    system: "modern",
    awardedBy: "Universities, under the NMC's Post-Graduate Medical Education Regulations",
    duration: "3 years after MD or DNB (a few institutions run 6-year courses after MBBS)",
    entry: "NEET-SS",
    registerSlug: NMC,
    pattern: "^DM(\\(|$)",
    standfirst: "The DM is the super-speciality degree of the medical specialities: cardiology, neurology, nephrology, gastroenterology, endocrinology and the rest.",
    about: [
      "The DM is the third tier of medical training in India: three more years after an MD or DNB, entered through NEET-SS, in a super-speciality — cardiology, neurology, nephrology, gastroenterology, endocrinology, medical oncology, neonatology, pulmonary medicine and others. A cardiologist, in the sense the register uses, is a doctor with a DM (Cardiology) or its DrNB equivalent; a physician with an interest in the heart is not. A few institutions run direct six-year courses after the MBBS that award the same degree.",
      "Because the DM is the qualification that separates a specialist from a super-specialist, it is the one a patient with a serious diagnosis should look for and the one most worth verifying. On this site the DM is recorded on cardiology, neurology, nephrology and gastroenterology profiles above all; the measured block below shows the branches and where their holders practise, and each profile says whether the qualification has been checked against the awarding university.",
    ],
    extraFaqs: [
      {
        q: "Is a DM a doctorate like a PhD?",
        a: "No. It is a clinical super-speciality degree — three years of supervised patient care and examination in one field. A PhD is a research degree. The two are sometimes confused because DM stands for \"Doctorate of Medicine\".",
      },
    ],
    checkedOn: CHECKED,
    sources: [SOURCE_NMC_PGMER, SOURCE_NMC_IMR, SOURCE_NMC_COURSES],
    related: ["mch", "md", "drnb"],
  }),
  qualification({
    slug: "mch",
    abbr: "MCh",
    name: "Magister Chirurgiae (Master of Chirurgiae)",
    kind: "superspecialty",
    system: "modern",
    awardedBy: "Universities, under the NMC's Post-Graduate Medical Education Regulations",
    duration: "3 years after MS or DNB (a few institutions run 6-year courses after MBBS)",
    entry: "NEET-SS",
    registerSlug: NMC,
    pattern: "^MCH(\\(|$)",
    standfirst: "The MCh is the super-speciality degree of the surgical specialities: neurosurgery, urology, plastic, cardiothoracic, paediatric and GI surgery.",
    about: [
      "The MCh is the surgical super-speciality degree, the counterpart of the [DM](/qualifications/dm): three years after an MS or DNB in a branch such as neurosurgery, urology, plastic surgery, cardiothoracic and vascular surgery, paediatric surgery, surgical gastroenterology or surgical oncology, entered through NEET-SS. A neurosurgeon is a doctor with an MCh (Neurosurgery) or its DrNB equivalent; a general surgeon operates on many things but is not one.",
      "The MCh is the qualification to look for when a surgery is specialised — a kidney, a spine, a child's heart — and the one most worth verifying against the awarding university. On this site MCh holders cluster in neurosurgery, urology and plastic surgery; the measured block below shows the branches and cities.",
    ],
    extraFaqs: [
      {
        q: "Why is it written MCh and not MS?",
        a: "Chirurgiae is Latin for \"of surgery\"; the degree keeps the old university form to distinguish it from the broad-speciality MS. Both are surgical; the MCh is the higher one.",
      },
    ],
    checkedOn: CHECKED,
    sources: [SOURCE_NMC_PGMER, SOURCE_NMC_IMR, SOURCE_NMC_COURSES],
    related: ["dm", "ms", "drnb"],
  }),
  qualification({
    slug: "drnb",
    abbr: "DrNB",
    name: "Doctorate of National Board",
    kind: "superspecialty",
    system: "modern",
    awardedBy: "National Board of Examinations in Medical Sciences",
    duration: "3 years after MD, MS or DNB",
    entry: "NEET-SS",
    registerSlug: NMC,
    pattern: "^DRNB(\\(|$)",
    standfirst: "The DrNB is the National Board's super-speciality qualification, equivalent to the DM and MCh, trained in accredited hospitals.",
    about: [
      "The DrNB is to the [DNB](/qualifications/dnb) what the [DM](/qualifications/dm) and [MCh](/qualifications/mch) are to the MD and MS: the super-speciality tier, awarded by the National Board of Examinations in Medical Sciences after three years of training in an accredited hospital and entered through NEET-SS. Older certificates for the same training read \"DNB\" with the super-speciality in brackets — DNB (Cardiology), DNB (Urology) — and profiles here carry both forms; the DrNB name is the newer one.",
      "The NMC recognises it as equivalent to the DM or MCh in the same field. Holders are found in the corporate hospitals that run National Board training programmes, which is where most of the DrNB profiles on this site practise.",
    ],
    extraFaqs: [
      {
        q: "Is DNB (Cardiology) the same as DrNB (Cardiology)?",
        a: "Yes. The Board renamed its super-speciality qualification DrNB; certificates issued before the change say DNB with the super-speciality in brackets. Both are super-speciality qualifications equivalent to the DM.",
      },
    ],
    checkedOn: CHECKED,
    sources: [SOURCE_NMC_PGMER, SOURCE_NMC_IMR],
    related: ["dnb", "dm", "mch"],
  }),
  qualification({
    slug: "fnb",
    abbr: "FNB",
    name: "Fellow of National Board",
    kind: "fellowship",
    system: "modern",
    awardedBy: "National Board of Examinations in Medical Sciences",
    duration: "2 years after a postgraduate degree",
    registerSlug: NMC,
    pattern: "^FNB(\\(|$)",
    standfirst: "The FNB is the National Board's two-year fellowship in a narrow field — a real, examined qualification, but a fellowship rather than a degree.",
    about: [
      "The Fellow of National Board is a post-doctoral fellowship of the National Board of Examinations in Medical Sciences: two years of training and an examination in a sub-speciality narrower than a DM or MCh — reproductive medicine, spine surgery, paediatric cardiology, critical care, minimal access surgery and others — taken after a postgraduate degree. Unlike most things called \"fellowship\" on a doctor's letterhead, it is examined and accredited by a statutory body, which is why it is listed here among the qualifications rather than the memberships.",
      "It is still a fellowship, not a degree: it adds a field of practice to a specialist, it does not make one. An FNB (Minimal Access Surgery) holder is a surgeon with a recognised further training; the surgical degree underneath is what licenses the surgery.",
    ],
    checkedOn: CHECKED,
    sources: [SOURCE_NMC_IMR],
    related: ["dnb", "drnb", "fmas"],
  }),
];
