import { SOURCE_NMC_IMR, qualification } from "@/lib/qualifications/build";
import type { QualificationEntry } from "@/lib/qualifications/types";

const CHECKED = "25 Sep 2026";
const NMC = "national-medical-commission";
const SECOND_SCHEDULE = { label: "NMC — The Second Schedule of the Indian Medical Council Act (recognised foreign qualifications)", url: "https://nmc.org.in/page/nmc-act-erstwhile-mci-acts-amendments-the-second-schedule-of-imc-act" };

/** Dental, AYUSH and allied-health degrees; Royal College qualifications; fellowships and memberships; the PhD. */
export const OTHER_QUALIFICATIONS: QualificationEntry[] = [
  qualification({
    slug: "bds",
    abbr: "BDS",
    name: "Bachelor of Dental Surgery",
    kind: "primary",
    system: "dental",
    awardedBy: "Universities, under National Dental Commission regulations",
    duration: "4 years plus a one-year internship",
    entry: "NEET-UG",
    registerSlug: "national-dental-commission",
    pattern: "^BDS$",
    standfirst: "The BDS is the primary dental degree in India; a BDS holder is a dentist registered with a state dental council, not a medical doctor.",
    about: [
      "The BDS is the primary qualification of dentistry: four years of study and a year of internship, entered through NEET-UG, awarded by universities under regulations now made by the [National Dental Commission](/registers/national-dental-commission). A BDS holder registers with a state dental council and may practise general dentistry — fillings, extractions, root canals, crowns, cleaning. The [MDS](/qualifications/mds) is the three-year postgraduate degree that makes a dental specialist.",
      "Dentists use the title \"Dr\", and patients sometimes assume a dental qualification is a medical one. It is not: a BDS holder is not on the medical register, cannot prescribe outside dentistry, and is regulated by a different body. On this site dentists are listed under dentistry, with the BDS as the primary qualification and the registering council named on each profile.",
    ],
    extraFaqs: [
      {
        q: "Is a dentist a doctor?",
        a: "A dentist is a doctor of dental surgery, registered with a dental council, and entitled to the title. A dentist is not a medical doctor and is not on the medical register; the qualification and the register on the profile tell you which you are looking at.",
      },
    ],
    checkedOn: CHECKED,
    related: ["mds", "mbbs"],
  }),
  qualification({
    slug: "mds",
    abbr: "MDS",
    name: "Master of Dental Surgery",
    kind: "postgraduate",
    system: "dental",
    awardedBy: "Universities, under National Dental Commission regulations",
    duration: "3 years after BDS",
    entry: "NEET-MDS",
    registerSlug: "national-dental-commission",
    pattern: "^MDS(\\(|$)",
    standfirst: "The MDS is the three-year postgraduate dental degree; its branches — orthodontics, oral surgery, prosthodontics, endodontics — are the dental specialities.",
    about: [
      "The MDS is the postgraduate degree of dentistry: three years after the [BDS](/qualifications/bds), entered through NEET-MDS, in one of the recognised branches — orthodontics, oral and maxillofacial surgery, prosthodontics, conservative dentistry and endodontics, periodontics, paediatric dentistry, oral pathology, oral medicine and radiology, public health dentistry. An MDS (Orthodontics) holder is an orthodontist; an MDS (Oral and Maxillofacial Surgery) holder is the surgeon who removes impacted wisdom teeth and repairs jaw fractures.",
      "As with the medical MD, the branch is what matters and it is written in brackets. The measured block below shows which branches the MDS holders on this site record; the [orthodontics](/qualifications/mds-orthodontics) and [oral and maxillofacial surgery](/qualifications/mds-oral-maxillofacial-surgery) branches have pages of their own.",
      "A patient meets an MDS holder when a general dentist refers on: to an orthodontist for braces, an oral surgeon for an impacted tooth, a periodontist for gum disease, an endodontist for a difficult root canal, a prosthodontist for implants and dentures. Any BDS holder may do all of these; the MDS is three years of training in one of them, and the degree on the profile is what tells you which you are seeing.",
    ],
    checkedOn: CHECKED,
    related: ["bds", "mds-orthodontics", "mds-oral-maxillofacial-surgery"],
  }),
  qualification({
    slug: "bams",
    abbr: "BAMS",
    name: "Bachelor of Ayurvedic Medicine and Surgery",
    kind: "primary",
    system: "ayush",
    awardedBy: "Universities, under NCISM regulations",
    duration: "4½ years plus a one-year internship",
    entry: "NEET-UG",
    registerSlug: "national-commission-for-indian-system-of-medicine",
    pattern: "^BAMS$",
    standfirst: "The BAMS is the primary degree of Ayurveda; its holder registers with a state Ayurveda board, not a medical council, and practises Ayurveda.",
    about: [
      "The BAMS is the primary qualification in Ayurveda: four and a half years of study and a year of internship, entered through NEET-UG, awarded by universities under regulations now made by the [National Commission for Indian System of Medicine](/registers/national-commission-for-indian-system-of-medicine). A BAMS holder registers with a state board of Indian medicine and is licensed to practise Ayurveda. On this site BAMS holders are listed under AYUSH, and they are numerous — the second most common primary degree after the MBBS, concentrated in Madhya Pradesh.",
      "What a BAMS does not do is license the practice of modern medicine. Whether and where a BAMS holder may prescribe modern drugs has been contested state by state and in the courts, and the position varies; this site records the system of medicine on every profile and lists AYUSH practitioners separately from physicians so that a search for one does not return the other.",
    ],
    extraFaqs: [
      {
        q: "Is a BAMS holder a doctor?",
        a: "A BAMS holder is a registered practitioner of Ayurveda and uses the title \"Dr\". They are not on the medical register and are not a doctor of modern medicine; the profile says which system a practitioner is registered in.",
      },
    ],
    checkedOn: CHECKED,
    related: ["bhms", "bums", "mbbs"],
  }),
  qualification({
    slug: "bhms",
    abbr: "BHMS",
    name: "Bachelor of Homoeopathic Medicine and Surgery",
    kind: "primary",
    system: "ayush",
    awardedBy: "Universities, under National Commission for Homoeopathy regulations",
    duration: "4½ years plus a one-year internship",
    entry: "NEET-UG",
    registerSlug: "national-commission-for-homoeopathy",
    pattern: "^BHMS$",
    standfirst: "The BHMS is the primary degree of homoeopathy; its holder registers with a state homoeopathy board and practises homoeopathy, not modern medicine.",
    about: [
      "The BHMS is the primary qualification in homoeopathy: four and a half years of study and a year of internship, entered through NEET-UG, awarded by universities under regulations made by the [National Commission for Homoeopathy](/registers/national-commission-for-homoeopathy). A BHMS holder registers with a state homoeopathy board and is licensed to practise homoeopathy. The MD (Homoeopathy) is the postgraduate degree in the system, and the [DHMS](/qualifications/dhms) an older diploma.",
      "A BHMS holder is not on the medical register and does not hold a licence to practise modern medicine. On this site homoeopaths are listed under AYUSH with the system stated, so that a search for a physician does not return a homoeopath and the reverse.",
      "The measured block below shows how many homoeopaths on this site record the BHMS and where they practise; a large share are in Madhya Pradesh, which is where the source data is deepest. A profile that records a BHMS together with a state medical council registration is carrying a contradiction, and is worth reporting through the corrections process.",
    ],
    checkedOn: CHECKED,
    related: ["dhms", "bams", "mbbs"],
  }),
  qualification({
    slug: "bums",
    abbr: "BUMS",
    name: "Bachelor of Unani Medicine and Surgery",
    kind: "primary",
    system: "ayush",
    awardedBy: "Universities, under NCISM regulations",
    duration: "4½ years plus a one-year internship",
    entry: "NEET-UG",
    registerSlug: "national-commission-for-indian-system-of-medicine",
    pattern: "^BUMS$",
    standfirst: "The BUMS is the primary degree of Unani medicine; its holder registers with a state board under the NCISM and practises Unani.",
    about: [
      "The BUMS is the primary qualification in Unani medicine, the Graeco-Arabic system practised in India for centuries: four and a half years of study and a year of internship, entered through NEET-UG, awarded by universities under regulations made by the [National Commission for Indian System of Medicine](/registers/national-commission-for-indian-system-of-medicine). A BUMS holder registers with a state board of Indian medicine and practises Unani. The BAMS is the Ayurveda equivalent and the BSMS the Siddha one.",
      "A BUMS holder is not on the medical register. On this site Unani practitioners are listed under AYUSH with the system stated; they are fewer than Ayurveda or homoeopathy practitioners, and the measured block below shows where they are.",
      "Unani practice in India is concentrated in a few states and cities, and the BUMS is taught in a smaller number of colleges than the BAMS or BHMS, which is why the count here is small. A BUMS holder registered with a state board is a qualified practitioner of Unani; the qualification does not license the prescription of modern-medicine drugs, and the profile records the system so that a reader is never in doubt which they are looking at.",
    ],
    checkedOn: CHECKED,
    related: ["bams", "bhms"],
  }),
  qualification({
    slug: "dhms",
    abbr: "DHMS",
    name: "Diploma in Homoeopathic Medicine and Surgery",
    kind: "diploma",
    system: "ayush",
    awardedBy: "State boards of homoeopathy (historic)",
    registerSlug: "national-commission-for-homoeopathy",
    pattern: "^DHMS$",
    standfirst: "The DHMS is an older diploma in homoeopathy that predates the BHMS degree; its holders are registered homoeopaths, mostly senior ones.",
    about: [
      "The DHMS is a diploma in homoeopathy awarded by state boards before the degree course, the [BHMS](/qualifications/bhms), became the standard primary qualification. Holders were registered on state homoeopathy registers and remain so; as far as this site can establish the course is no longer offered for new admission, and the DHMS holders here are correspondingly senior. It is a homoeopathy qualification and licenses homoeopathy only.",
      "On this site the DHMS is recorded on a substantial number of homoeopathy profiles, chiefly in Madhya Pradesh. A DHMS holder is not on the medical register and is listed under AYUSH with the system stated.",
      "Because the DHMS is a diploma rather than a degree, a homoeopath who holds one and no BHMS has a shorter formal training than a BHMS holder; both are registrable and both practise homoeopathy. The year on the profile, where the source data carried it, is the way to tell an old diploma from a recent degree.",
    ],
    checkedOn: CHECKED,
    related: ["bhms", "bams"],
  }),
  qualification({
    slug: "bpt",
    abbr: "BPT",
    name: "Bachelor of Physiotherapy",
    kind: "primary",
    system: "allied",
    awardedBy: "Universities",
    duration: "4 years plus a six-month internship (varies by university)",
    registerSlug: "national-commission-for-allied-and-healthcare-professions",
    pattern: "^BPT$",
    standfirst: "The BPT is the primary physiotherapy degree; its holder is a physiotherapist, registered with a state council where one exists — not a medical doctor.",
    about: [
      "The BPT is the primary qualification in physiotherapy: a four-year university degree followed by an internship of about six months, the length varying by university. A BPT holder is a physiotherapist — they treat movement and pain with exercise, manual therapy and electrotherapy, and work in rehabilitation after surgery, injury and stroke. Registration is with a state physiotherapy council where one exists, or with the state allied and healthcare councils being set up under the [National Commission for Allied and Healthcare Professions](/registers/national-commission-for-allied-and-healthcare-professions) Act, 2021; in many states only a professional-body membership is currently available.",
      "A BPT holder is not on the medical register and does not prescribe medicines. Whether physiotherapists should use the title \"Dr\" is contested, and this site does not take a side: it records the qualification, the registering body, and the profession. The [MPT](/qualifications/mpt) is the two-year postgraduate degree in a physiotherapy speciality.",
    ],
    checkedOn: CHECKED,
    related: ["mpt", "mbbs"],
  }),
  qualification({
    slug: "mpt",
    abbr: "MPT",
    name: "Master of Physiotherapy",
    kind: "postgraduate",
    system: "allied",
    awardedBy: "Universities",
    duration: "2 years after BPT",
    registerSlug: "national-commission-for-allied-and-healthcare-professions",
    pattern: "^MPT(\\(|$)",
    standfirst: "The MPT is the two-year postgraduate physiotherapy degree in a speciality such as orthopaedics, neurology, sports or cardiopulmonary physiotherapy.",
    about: [
      "The MPT is the postgraduate degree of physiotherapy: two years after the [BPT](/qualifications/bpt), in a speciality — musculoskeletal or orthopaedic physiotherapy, neurological, cardiopulmonary, sports, paediatric, community or women's health. An MPT holder is a specialist physiotherapist, and in hospitals the MPT is the usual qualification for a senior or teaching post. The branch is usually written in brackets, and the measured block below shows which branches the MPT holders on this site record.",
      "The MPT does not change the profession's regulatory position: an MPT holder is a physiotherapist, registered where a council exists, and not a medical doctor.",
      "On this site MPT holders are a minority of the physiotherapists, most of whom record a BPT alone. The MPT is worth looking for when the problem is specialised — a sports injury, a stroke, a child with cerebral palsy — because the branch in brackets says what the physiotherapist trained in beyond the general degree.",
    ],
    checkedOn: CHECKED,
    related: ["bpt"],
  }),
  qualification({
    slug: "frcs",
    abbr: "FRCS",
    name: "Fellow of the Royal College of Surgeons",
    kind: "fellowship",
    system: "modern",
    awardedBy: "The Royal Colleges of Surgeons of England, Edinburgh, Glasgow and Ireland",
    entry: "Examination, after surgical training",
    registerSlug: NMC,
    pattern: "^FRCS",
    standfirst: "The FRCS is a surgical qualification of the British and Irish Royal Colleges, recognised in India; it is a fellowship by examination, not a membership.",
    about: [
      "The FRCS is awarded by examination by the Royal Colleges of Surgeons of England, Edinburgh, Glasgow and Ireland, and unlike most fellowships on a doctor's letterhead it is a recognised surgical qualification: the FRCS of those colleges appears among the foreign qualifications listed in the Second Schedule of the Indian Medical Council Act, which the National Medical Commission inherited. An Indian surgeon with an FRCS has typically trained or worked in the United Kingdom or Ireland and sat the colleges' examination; older FRCS certificates were the general surgical fellowship, newer ones are intercollegiate and speciality-specific — FRCS (Orth), FRCS (Urol) and so on.",
      "The FRCS is distinct from the [MRCS](/qualifications/mrcs), the colleges' membership examination taken earlier in training, and from the many Indian fellowships that borrow the word. On this site the FRCS is recorded chiefly on surgeons in the corporate hospitals, and whether it has been checked with the college is stated on each profile.",
    ],
    extraFaqs: [
      {
        q: "Is an FRCS higher than an MS?",
        a: "They are different routes to the same thing. The MS is the Indian university postgraduate degree in surgery; the FRCS is the Royal Colleges' examined fellowship, taken after surgical training in the British system. An FRCS holder practising in India registers the qualification with a state medical council as a recognised foreign qualification.",
      },
    ],
    checkedOn: CHECKED,
    sources: [SECOND_SCHEDULE, SOURCE_NMC_IMR],
    related: ["mrcs", "mrcp", "ms"],
  }),
  qualification({
    slug: "mrcp",
    abbr: "MRCP",
    name: "Member of the Royal College of Physicians (UK)",
    kind: "fellowship",
    system: "modern",
    awardedBy: "The Royal Colleges of Physicians of the United Kingdom",
    entry: "Examination, after the MBBS and clinical experience",
    registerSlug: NMC,
    pattern: "^MRCP(?!CH)",
    standfirst: "The MRCP (UK) is the British physicians' examination, recognised in India as a postgraduate qualification in medicine; a membership by examination.",
    about: [
      "The MRCP (UK) is the examination of the Royal Colleges of Physicians of the United Kingdom, in three parts, taken after the MBBS and some years of clinical work. Although it is called a membership, it is an examined qualification and the MRCP of the British colleges appears among the recognised foreign qualifications in the Second Schedule of the Indian Medical Council Act; an Indian physician with an MRCP has typically trained in the UK, or sat the examination at one of the overseas centres, and registers it with a state medical council as a postgraduate qualification in medicine.",
      "The MRCP is not a super-speciality qualification — an MRCP holder is a physician, and a cardiologist needs the [DM](/qualifications/dm) or its equivalent on top. On this site the MRCP is recorded mainly on physicians and cardiologists in the corporate hospitals; the paediatric equivalent, the MRCPCH, is a separate examination and is not counted here.",
    ],
    checkedOn: CHECKED,
    sources: [SECOND_SCHEDULE, SOURCE_NMC_IMR],
    related: ["frcs", "md", "mrcs"],
  }),
  qualification({
    slug: "mrcs",
    abbr: "MRCS",
    name: "Member of the Royal College of Surgeons",
    kind: "membership",
    system: "modern",
    awardedBy: "The Royal Colleges of Surgeons of England, Edinburgh, Glasgow and Ireland",
    entry: "Examination, early in surgical training",
    registerSlug: NMC,
    pattern: "^MRCS",
    standfirst: "The MRCS is the Royal Colleges' surgical membership examination taken early in training — a real examination, but not a specialist qualification.",
    about: [
      "The MRCS is the membership examination of the Royal Colleges of Surgeons, taken in the early years of surgical training in the British system, before speciality training begins. It tests the basic sciences and skills of surgery; it does not make its holder a specialist surgeon, which is what the [FRCS](/qualifications/frcs), taken years later, does. An Indian surgeon with an MRCS has usually sat the examination in the UK or at an overseas centre, and may or may not have gone on to the FRCS.",
      "For a patient the distinction matters: MRCS on a letterhead beside an MS is a mark of extra examination; MRCS without any Indian or recognised postgraduate surgical degree is not a specialist qualification. On this site the MRCS is shown alongside the qualifications, and the specialist degree, where there is one, is the fact to look at.",
    ],
    checkedOn: CHECKED,
    sources: [SOURCE_NMC_IMR],
    related: ["frcs", "ms", "mrcp"],
  }),
  qualification({
    slug: "mrcog",
    abbr: "MRCOG",
    name: "Member of the Royal College of Obstetricians and Gynaecologists",
    kind: "fellowship",
    system: "modern",
    awardedBy: "The Royal College of Obstetricians and Gynaecologists, London",
    entry: "Examination, after training in obstetrics and gynaecology",
    registerSlug: NMC,
    pattern: "^MRCOG",
    standfirst: "The MRCOG is the London college's examined qualification in obstetrics and gynaecology, recognised in India; a membership by examination.",
    about: [
      "The MRCOG is the examination of the Royal College of Obstetricians and Gynaecologists in London, in parts, taken after training in the speciality. Like the MRCP it is called a membership but is an examined specialist qualification, and the MRCOG appears among the recognised foreign qualifications in the Second Schedule of the Indian Medical Council Act. An Indian gynaecologist with an MRCOG has usually trained in the UK or sat the examination at an overseas centre, and registers it with a state medical council as a postgraduate qualification.",
      "On this site the MRCOG is recorded on a modest number of gynaecologists, mostly in the corporate hospitals of Bengaluru. The Indian equivalents are the [MS or MD in Obstetrics and Gynaecology](/qualifications/md-ms-obstetrics-gynaecology) and the [DNB](/qualifications/dnb); the [DGO](/qualifications/dgo) is the two-year diploma.",
    ],
    checkedOn: CHECKED,
    sources: [SECOND_SCHEDULE, SOURCE_NMC_IMR],
    related: ["md-ms-obstetrics-gynaecology", "dgo", "mrcp"],
  }),
  qualification({
    slug: "mnams",
    abbr: "MNAMS",
    name: "Member of the National Academy of Medical Sciences",
    kind: "membership",
    system: "modern",
    awardedBy: "National Academy of Medical Sciences (India)",
    registerSlug: NMC,
    pattern: "^MNAMS",
    standfirst: "The MNAMS is membership of India's National Academy of Medical Sciences, historically conferred on doctors who passed the National Board's examinations.",
    about: [
      "The MNAMS is membership of the National Academy of Medical Sciences, a body set up to promote medical education and research and, for many years, the parent of the National Board of Examinations. Doctors who passed the Board's examinations were admitted as members, which is why an MNAMS on a profile usually sits beside a [DNB](/qualifications/dnb) and dates the doctor's training. It is a membership of an academy rather than a degree, and it is not a qualification in a branch of medicine; the DNB beside it is.",
      "On this site the MNAMS is recorded on a few dozen profiles, mostly senior specialists in Bengaluru and Madhya Pradesh. It is shown alongside the qualifications and never in place of them.",
    ],
    checkedOn: CHECKED,
    sources: [SOURCE_NMC_IMR],
    related: ["dnb", "fics", "fmas"],
  }),
  qualification({
    slug: "fics",
    abbr: "FICS",
    name: "Fellow of the International College of Surgeons",
    kind: "membership",
    system: "modern",
    awardedBy: "International College of Surgeons, Chicago",
    registerSlug: NMC,
    pattern: "^FICS",
    standfirst: "The FICS is fellowship of a Chicago-based international surgical society — a membership of a society, not an examined or recognised qualification.",
    about: [
      "The FICS is a fellowship of the International College of Surgeons, an international surgical society based in Chicago with national sections, including one in India. Fellowship is by application on the basis of surgical qualifications and practice, not by examination, and it is not on any schedule of qualifications the National Medical Commission recognises. It tells you the surgeon joined a society that admits qualified surgeons; it does not tell you anything the surgeon's degree does not.",
      "On this site the FICS is recorded on a few dozen surgeons, mainly senior general surgeons. It is shown after the qualifications, and the MS, DNB or MCh beside it is the fact that licenses the surgery.",
    ],
    checkedOn: CHECKED,
    sources: [],
    related: ["frcs", "fiages", "fmas"],
  }),
  qualification({
    slug: "fmas",
    abbr: "FMAS",
    name: "Fellowship in Minimal Access Surgery",
    kind: "fellowship",
    system: "modern",
    awardedBy: "Private training institutes (chiefly the World Laparoscopy Hospital, Gurugram)",
    registerSlug: NMC,
    pattern: "^FMAS",
    standfirst: "The FMAS is a short laparoscopic-surgery course from a private institute — real hands-on training, but not a recognised qualification.",
    about: [
      "The FMAS — Fellowship in Minimal Access Surgery — is a short course in laparoscopic surgery run by private training institutes, most prominently the World Laparoscopy Hospital in Gurugram, and taken by qualified surgeons and gynaecologists who want to add or refresh laparoscopic skills. Courses run for days or weeks rather than years. It is genuine training, and it is common on the letterheads of gynaecologists and general surgeons across India; it is not a qualification any statutory body recognises, and it is not the two-year, examined [FNB](/qualifications/fnb) in minimal access surgery that the National Board awards.",
      "On this site the FMAS is one of the most frequently recorded fellowships, chiefly on gynaecologists and general surgeons in Madhya Pradesh. It is shown after the qualifications; the MS, DGO, DNB or MD beside it is what licenses the surgery.",
    ],
    extraFaqs: [
      {
        q: "Does an FMAS mean the surgeon is a laparoscopic specialist?",
        a: "It means the surgeon attended a laparoscopic training course. Skill in laparoscopy comes from the surgical degree, the years of practice and the hospital's case volume; the FMAS certificate is evidence of interest and some instruction, not of a specialist qualification.",
      },
    ],
    checkedOn: CHECKED,
    sources: [],
    related: ["fiages", "fnb", "ms"],
  }),
  qualification({
    slug: "fiages",
    abbr: "FIAGES",
    name: "Fellow of the Indian Association of Gastrointestinal Endo-Surgeons",
    kind: "fellowship",
    system: "modern",
    awardedBy: "Indian Association of Gastrointestinal Endo-Surgeons",
    registerSlug: NMC,
    pattern: "^FIAGES",
    standfirst: "The FIAGES is a fellowship of the Indian laparoscopic surgeons' association, awarded after a training programme — a society fellowship, not a degree.",
    about: [
      "The FIAGES is a fellowship of the Indian Association of Gastrointestinal Endo-Surgeons, the professional association of laparoscopic and endoscopic surgeons in India, awarded to member surgeons who complete the association's training programme in a recognised centre. It is a mark of structured laparoscopic training within the profession's own association, and in that sense carries more than the private-institute courses; it is still a society fellowship, not a qualification the National Medical Commission recognises, and it sits beside a surgical degree rather than replacing one.",
      "On this site the FIAGES is recorded on general surgeons above all, most of them in Madhya Pradesh. It is shown after the qualifications.",
    ],
    checkedOn: CHECKED,
    sources: [],
    related: ["fmas", "fics", "ms-general-surgery"],
  }),
  qualification({
    slug: "fccp",
    abbr: "FCCP",
    name: "Fellow of the American College of Chest Physicians",
    kind: "membership",
    system: "modern",
    awardedBy: "American College of Chest Physicians",
    registerSlug: NMC,
    pattern: "^FCCP",
    standfirst: "The FCCP is a membership grade of the American College of Chest Physicians, held by pulmonologists — a society fellowship, not an examined qualification.",
    about: [
      "The FCCP is the fellowship grade of membership of the American College of Chest Physicians, the US professional society for pulmonary, critical-care and sleep medicine. It is granted on application to members with the relevant qualifications and practice; there is no examination, and it is not on any schedule of qualifications the National Medical Commission recognises. On a chest physician's letterhead it signals membership of the international society in the field, and nothing more than the doctor's degree already says.",
      "On this site the FCCP is recorded on pulmonologists and a few physicians. The qualification that makes a pulmonologist is the MD in Pulmonary Medicine, the [DTCD](/qualifications/dtcd) or the DNB; the FCCP is shown after them.",
    ],
    checkedOn: CHECKED,
    sources: [],
    related: ["dtcd", "md", "fics"],
  }),
  qualification({
    slug: "fage",
    abbr: "FAGE",
    name: "Fellow of the Academy of General Education",
    kind: "membership",
    system: "modern",
    awardedBy: "Academy of General Education, Manipal",
    registerSlug: NMC,
    pattern: "^FAGE",
    standfirst: "The FAGE is a fellowship of Manipal's Academy of General Education, conferred on its graduates — a mark of where a doctor trained, not a qualification.",
    about: [
      "The FAGE is a fellowship of the Academy of General Education, Manipal, the trust behind Kasturba Medical College and the other Manipal institutions, conferred on their graduates. It appears on the letterheads of many Manipal-trained doctors in Karnataka. It is not a qualification in any branch of medicine and not an examination; it tells you where the doctor studied, which the degree line usually tells you too.",
      "On this site the FAGE is recorded almost entirely on doctors in Bengaluru and coastal Karnataka. It is shown after the qualifications, and the measured block below makes the pattern visible.",
    ],
    checkedOn: CHECKED,
    sources: [],
    related: ["mbbs", "fics"],
  }),
  qualification({
    slug: "phd",
    abbr: "PhD",
    name: "Doctor of Philosophy",
    kind: "doctorate",
    system: "modern",
    awardedBy: "Universities",
    duration: "3 to 5 years of supervised research",
    registerSlug: NMC,
    pattern: "^PHD",
    standfirst: "A PhD is a research degree, not a clinical one; on a doctor's profile it records research training and does not by itself make a specialist.",
    about: [
      "A PhD is a research degree awarded by a university for a thesis, typically after three to five years of supervised work. On a doctor's profile it records that the holder has done research training in a field — pharmacology, physiology, community medicine, a clinical question — and it is a real and demanding qualification. It is not a clinical qualification: it does not license practice, it is not a speciality, and it is not the same as the clinical [DM](/qualifications/dm), which is also expanded as \"Doctorate of Medicine\". Nor does a PhD alone entitle its holder to practise medicine; an MBBS underneath is what does that.",
      "On this site the PhD is recorded on a modest number of profiles, many of them teaching doctors and laboratory specialists. Clinical psychologists sometimes hold a PhD or PsyD in psychology, which is their professional doctorate and a different thing again; the registering body on the profile tells you which profession you are looking at.",
    ],
    checkedOn: CHECKED,
    sources: [],
    related: ["dm", "md", "mbbs"],
  }),
];
