import { stateMedicalCouncil } from "@/lib/registers/build";
import type { RegisterEntry } from "@/lib/registers/types";

const CHECKED = "25 Sep 2026";

/** The remaining state councils on the NMC list, plus Kerala under its current name. */
export const STATE_MEDICAL_COUNCILS_2: RegisterEntry[] = [
  stateMedicalCouncil({
    slug: "kerala-state-medical-council",
    name: "Kerala State Medical Council",
    short: "KSMC",
    state: { name: "Kerala", slug: "kerala" },
    office: "Combined Council Building, Red Cross Road, Thiruvananthapuram 695035",
    website: "https://medicalcouncil.kerala.gov.in",
    aliases: ["Travancore-Cochin Medical Council", "Travancore Cochin Medical Council", "Travancore Medical Council", "Travancore Cochin Medical Council Trivandrum", "KSMC"],
    about: [
      "Kerala's modern-medicine register is kept by the Kerala State Medical Council, the successor to the Travancore-Cochin Medical Councils that the Travancore-Cochin Medical Practitioners Act, 1953 created; the 1953 Act was replaced by the Kerala State Medical Practitioners Act, 2021. The NMC's own list still shows the council under its old name, \"Travancore Cochin Medical Council, Trivandrum\", with no contact data — so a Kerala doctor's certificate may carry either name, and older ones carry the older one.",
      "The council's office is the Combined Council Building on Red Cross Road, Thiruvananthapuram, and its site is medicalcouncil.kerala.gov.in, where registration services run through an online system. The public search for Kerala numbers is the NMC register; when searching there, look for the council under the Travancore-Cochin name if the Kerala name is not offered.",
    ],
    checkedOn: CHECKED,
    extraSources: [
      { label: "Kerala State Medical Council — contact page", url: "https://medicalcouncil.kerala.gov.in/contact-us/" },
      { label: "Government of Kerala, Health Department — Kerala State Medical Councils", url: "https://health.kerala.gov.in/" },
    ],
    related: ["tamil-nadu-medical-council", "karnataka-medical-council", "national-medical-commission"],
  }),
  stateMedicalCouncil({
    slug: "assam-medical-council",
    name: "Assam Medical Council",
    state: { name: "Assam", slug: "assam" },
    office: "Khanapara, Guwahati 781022",
    about: [
      "The Assam Medical Council, at Khanapara in Guwahati, registers doctors of modern medicine for Assam and is the largest of the north-eastern registers. The NMC's list shows no website for it. The public search for Assam numbers is therefore the NMC register, and the council office is the fallback when a record is missing.",
    ],
    checkedOn: CHECKED,
    related: ["national-medical-commission", "west-bengal-medical-council", "manipur-medical-council"],
  }),
  stateMedicalCouncil({
    slug: "odisha-council-of-medical-registration",
    name: "Odisha Council of Medical Registration",
    short: "OCMR",
    state: { name: "Odisha", slug: "odisha" },
    office: "Block No. 11, Unit V, Bhubaneswar 751001",
    website: "https://www.ocmr.org",
    aliases: ["Orissa Council of Medical Registration", "Odisha Medical Council", "Orissa Medical Council", "OCMR"],
    about: [
      "Odisha's register is kept by the Odisha Council of Medical Registration in Bhubaneswar — a body whose name differs from the \"medical council\" pattern of most states, and which the NMC still lists under the older spelling \"Orissa\". Profiles on this site cite it under four spellings, all of which resolve here.",
      "The council's site is ocmr.org. The public search for OCMR numbers is the NMC register, where the council appears under its Orissa-era name.",
    ],
    checkedOn: CHECKED,
    related: ["national-medical-commission", "west-bengal-medical-council", "chhattisgarh-medical-council"],
  }),
  stateMedicalCouncil({
    slug: "punjab-medical-council",
    name: "Punjab Medical Council",
    short: "PMC",
    state: { name: "Punjab", slug: "punjab" },
    office: "Medical Education Bhawan, Sector 69, SAS Nagar (Mohali)",
    website: "https://www.punjabmedicalcouncil.com",
    aliases: ["PMC"],
    about: [
      "The Punjab Medical Council sits in Medical Education Bhawan at Sector 69, Mohali, and registers doctors of modern medicine for Punjab. Its site, punjabmedicalcouncil.com, is the one the NMC lists. Chandigarh, a union territory, does not appear on the NMC's list of state medical councils, and doctors practising in the tricity area most often hold a Punjab or Haryana registration.",
    ],
    checkedOn: CHECKED,
    related: ["haryana-medical-council", "national-medical-commission", "himachal-pradesh-medical-council"],
  }),
  stateMedicalCouncil({
    slug: "haryana-medical-council",
    name: "Haryana Medical Council",
    short: "HMC",
    state: { name: "Haryana", slug: "haryana" },
    office: "SCO 410, 2nd Floor, Sector 20, Panchkula 134116",
    website: "http://haryanamedicalcouncil.com",
    aliases: ["HMC"],
    about: [
      "The Haryana Medical Council is in Panchkula, and registers doctors of modern medicine for Haryana — including the many practising in Gurugram and Faridabad, who often also hold Delhi Medical Council registrations. The NMC lists the council's site as haryanamedicalcouncil.com. The public search for its numbers is the NMC register.",
    ],
    checkedOn: CHECKED,
    related: ["delhi-medical-council", "punjab-medical-council", "national-medical-commission"],
  }),
  stateMedicalCouncil({
    slug: "jharkhand-medical-council",
    name: "Jharkhand Medical Council",
    state: { name: "Jharkhand", slug: "jharkhand" },
    office: "Bariatu Road, Ranchi 834009",
    about: [
      "The Jharkhand Medical Council, on Bariatu Road in Ranchi, was formed after the state separated from Bihar in 2000; doctors registered before then in what is now Jharkhand hold Bihar Medical Council numbers, and a Ranchi or Jamshedpur doctor citing Bihar is not unusual. The NMC's list shows no website for the council, so the NMC register is the public search.",
    ],
    checkedOn: CHECKED,
    related: ["bihar-medical-council", "national-medical-commission", "west-bengal-medical-council"],
  }),
  stateMedicalCouncil({
    slug: "goa-medical-council",
    name: "Goa Medical Council",
    state: { name: "Goa", slug: "goa" },
    office: "Faculty Block, Goa Medical College Complex, Bambolim 403202",
    website: "https://www.goamedicalcouncil.com",
    about: [
      "The Goa Medical Council sits in the Goa Medical College complex at Bambolim and keeps one of the smallest state registers in the country. Its site is goamedicalcouncil.com, as listed by the NMC. Many doctors practising in Goa trained in Karnataka or Maharashtra and carry those registrations as well; all are searched on the NMC register in the same way.",
    ],
    checkedOn: CHECKED,
    related: ["maharashtra-medical-council", "karnataka-medical-council", "national-medical-commission"],
  }),
  stateMedicalCouncil({
    slug: "himachal-pradesh-medical-council",
    name: "Himachal Pradesh Medical Council",
    short: "HPMC",
    state: { name: "Himachal Pradesh", slug: "himachal-pradesh" },
    office: "Dulcedhum House, Folkland Estate, near IGMC, Lakkar Bazar, Shimla 171001",
    website: "https://www.hpsmc.org",
    aliases: ["Himanchal Pradesh Medical Council", "HPMC", "Himachal Pradesh State Medical Council"],
    about: [
      "The Himachal Pradesh Medical Council is in Lakkar Bazar, Shimla, near the Indira Gandhi Medical College. The NMC list spells it \"Himanchal\" and gives its site as hpsmc.org. The public search for HPMC numbers is the NMC register.",
    ],
    checkedOn: CHECKED,
    related: ["punjab-medical-council", "uttarakhand-medical-council", "national-medical-commission"],
  }),
  stateMedicalCouncil({
    slug: "jammu-and-kashmir-medical-council",
    name: "Jammu & Kashmir Medical Council",
    short: "JKMC",
    state: { name: "Jammu and Kashmir", slug: "jammu-and-kashmir" },
    office: "Gandhi Nagar, Jammu 180004 and Bemina, Srinagar 190018",
    website: "https://www.jkmedicalcouncil.in",
    aliases: ["Jammu and Kashmir Medical Council", "J&K Medical Council", "JKMC"],
    about: [
      "The Jammu & Kashmir Medical Council keeps two offices — Gandhi Nagar in Jammu and Bemina in Srinagar — reflecting the union territory's two seasonal capitals. The NMC lists its site as jkmedicalcouncil.in. The public search for its numbers is the NMC register.",
    ],
    checkedOn: CHECKED,
    related: ["punjab-medical-council", "himachal-pradesh-medical-council", "national-medical-commission"],
  }),
  stateMedicalCouncil({
    slug: "manipur-medical-council",
    name: "Manipur Medical Council",
    state: { name: "Manipur", slug: "manipur" },
    office: "Medical Directorate Complex, Lamphel, Imphal 795004",
    website: "https://www.manipurmedicalcouncil.org",
    about: [
      "The Manipur Medical Council is in the Medical Directorate complex at Lamphel, Imphal. The NMC lists its site as manipurmedicalcouncil.org and, unusually, names a consultant for IT among its contacts. The public search for Manipur numbers is the NMC register.",
    ],
    checkedOn: CHECKED,
    related: ["assam-medical-council", "mizoram-medical-council", "nagaland-medical-council"],
  }),
  stateMedicalCouncil({
    slug: "mizoram-medical-council",
    name: "Mizoram Medical Council",
    state: { name: "Mizoram", slug: "mizoram" },
    office: "Block B, Civil Hospital Aizawl, Dawrpui, Aizawl 796001",
    about: [
      "The Mizoram Medical Council sits inside Civil Hospital Aizawl. The NMC's list shows no website for it; the NMC register is the public search for Mizoram numbers and the council office at Dawrpui is the fallback.",
    ],
    checkedOn: CHECKED,
    related: ["manipur-medical-council", "assam-medical-council", "national-medical-commission"],
  }),
  stateMedicalCouncil({
    slug: "nagaland-medical-council",
    name: "Nagaland Medical Council",
    state: { name: "Nagaland", slug: "nagaland" },
    office: "PMTI Complex, Merhulietsa Colony, Kohima 797001",
    website: "https://nmc.nagaland.gov.in",
    about: [
      "The Nagaland Medical Council is in the PMTI complex at Kohima. The NMC lists its site as nmc.nagaland.gov.in — the abbreviation collides with the National Medical Commission's, so read the domain, not the initials. The public search for Nagaland numbers is the NMC register.",
    ],
    checkedOn: CHECKED,
    related: ["manipur-medical-council", "assam-medical-council", "national-medical-commission"],
  }),
  stateMedicalCouncil({
    slug: "sikkim-medical-council",
    name: "Sikkim Medical Council",
    state: { name: "Sikkim", slug: "sikkim" },
    office: "Library Building, STNM Hospital Complex, Gangtok 737101",
    about: [
      "The Sikkim Medical Council is in the STNM Hospital complex at Gangtok and keeps one of the smallest registers in the country. The NMC's list shows no website; the NMC register is the public search.",
    ],
    checkedOn: CHECKED,
    related: ["west-bengal-medical-council", "assam-medical-council", "national-medical-commission"],
  }),
  stateMedicalCouncil({
    slug: "tripura-state-medical-council",
    name: "Tripura State Medical Council",
    state: { name: "Tripura", slug: "tripura" },
    office: "Dr P. B. Das Memorial Building, Bidur Karta Chowmuhani, Agartala 799001",
    website: "http://tsmc.tripura.gov.in/",
    aliases: ["Tripura Medical Council"],
    about: [
      "The Tripura State Medical Council is in Agartala. Its initials, TSMC, are the same as Telangana's, which is one more reason to select the council by name rather than by abbreviation when searching. The NMC lists its site as tsmc.tripura.gov.in. The public search for Tripura numbers is the NMC register.",
    ],
    checkedOn: CHECKED,
    related: ["assam-medical-council", "west-bengal-medical-council", "telangana-state-medical-council"],
  }),
  stateMedicalCouncil({
    slug: "uttarakhand-medical-council",
    name: "Uttarakhand Medical Council",
    short: "UKMC",
    state: { name: "Uttarakhand", slug: "uttarakhand" },
    office: "Office of the Director General, Medical Health & FW, Danda Lakhond, Sahastradhara Road, Dehradun",
    website: "https://www.ukmedicalcouncil.org",
    aliases: ["Uttaranchal Medical Council", "UKMC"],
    about: [
      "The Uttarakhand Medical Council operates from the Director General of Medical Health's office at Dehradun. The state separated from Uttar Pradesh in 2000, so older doctors here hold Uttar Pradesh Medical Council numbers; certificates from the early years may carry the state's former name, Uttaranchal. The NMC lists the council's site as ukmedicalcouncil.org.",
    ],
    checkedOn: CHECKED,
    related: ["uttar-pradesh-medical-council", "himachal-pradesh-medical-council", "national-medical-commission"],
  }),
  stateMedicalCouncil({
    slug: "arunachal-pradesh-medical-council",
    name: "Arunachal Pradesh Medical Council",
    state: { name: "Arunachal Pradesh", slug: "arunachal-pradesh" },
    office: "Directorate of Health Services Complex, Naharlagun 791110",
    website: "http://arunapmc.nic.in",
    about: [
      "The Arunachal Pradesh Medical Council is in the Directorate of Health Services complex at Naharlagun, near Itanagar. The NMC lists its site as arunapmc.nic.in. The public search for its numbers is the NMC register; with a register this small, a missing record is more likely to be a synchronisation gap than a fake, and the council office is the right place to ask.",
    ],
    checkedOn: CHECKED,
    related: ["assam-medical-council", "nagaland-medical-council", "national-medical-commission"],
  }),
];
